### ISSUE TITLE
Feature suggestions a) paper link, b) cell symmetry constraint

### ISSUE THREAD

**Issue by nbehrnd** [chemistry/crystallography.io#7]
The two feature suggestions are based on observation on site [http://crystallography-online.com](http://crystallography-online.com) mentioned by the [COD](https://wiki.crystallography.net/codmirrors/). These could be implemented in either the more senior site (crystallography-online.com) or the one in construction ([https://crystallography.io/](https://crystallography.io/)).

- on crystallography-online.com, the COD entries are displayed interactively, and the source of the primary publication is mentioned. It would be a nice addition if either a) the primary source were hyperlinked to the journal, or if the paper's address would be recapitulated as doi to access the original publication with [Chemistry Reference Resolver](https://chemsearch.kovsky.net/help.php) or / and as hyperlink directly to the journal's entry.
- crystallography-online.com is set up to search in the COD by lattice parameters.  From the user's perspective, the search could be simplified by addition of a pull-down menu with the Bravais classes, including cubic all the way down to monoclinic.  The aim is that the selection of one of them would either fix certain values (e.g., cubic to set automatically alpha = beta = gamma = 90 degrees) and to require the user less of input (again for the example of a cubic unit cell, only one a, instead of (a, and b, and c).

Screen photos in the .zip archive provide some illustration.

[2020-12-18_documentation.zip](https://github.com/chemistry/crystallography.io/files/5717739/2020-12-18_documentation.zip)

**Comment by vreshch** [comment]
Hi @nbehrnd - thanks for the feedback. the first issue is resolved.
I've added link based on DOI as example here: https://crystallography.io/structure/1000000 
Concerning Unit Cell Additional constrains - it's on a way.

**Comment by nbehrnd** [comment]
The current implementation of the link looks good and works fine.
Thank you.
